### PR TITLE
Issue #65: java.lang.IllegalStateException: Duplicate key stop_remote_server

### LINKED ISSUE #65: java.lang.IllegalStateException: Duplicate key stop_remote_server
Hi. Seems like the newest version starts to throw

```
Caused by: java.lang.IllegalStateException: Duplicate key stop_remote_server (attempted merging values {args=[], types=[], doc=Stops the remote server.

The server may be configured so that users cannot stop it., tags=[]} and {args=[], types=[], doc=Stops the remote server.

The server may be configured so that users cannot stop it., tags=[]})
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.robotframework.remoteserver.servlet.ServerMethods.get_library_information(ServerMethods.java:205)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
	... 36 common frames omitted
```

I believe the reason is in https://github.com/robotframework/jrobotremoteserver/blob/82f904dccc9e77b9d0875ed87af72d815ffec2f8/src/main/java/org/robotframework/remoteserver/servlet/ServerMethods.java#L57
where the "stop_remote_server" is added to the ArrayList.
It has become an issue after https://github.com/robotframework/jrobotremoteserver/blob/82f904dccc9e77b9d0875ed87af72d815ffec2f8/src/main/java/org/robotframework/remoteserver/servlet/ServerMethods.java#L202 started to expect unique keyword names.

This can be reproduced by starting a server and executing some test against it multiple times without stopping the server in between.

Could be fixed by using a Set or calling contains before adding the "stop_remote_server" keyword.

### PR DESCRIPTION
**Pull request by lasselindqvist**
Fixes #65
Fix get_library_information when called multiple times
Also extends tests to cover this behaviour.

### CODE REVIEW

**Comment by mluyun** [comment]
Hi anyone who can review and merge this PR? We are also experiencing this error when running multiple tests

**Comment by lasselindqvist** [comment]
I can also release a fork of this in Maven Central under my namespace, but I would prefer this being maintained of course.

**Comment by lasselindqvist** [comment]
https://repo1.maven.org/maven2/io/github/lasselindqvist/jrobotremoteserver/4.2.0/ is a deployed version with this fix. I can also deploy any other needed fixes to this project in https://github.com/lasselindqvist/jrobotremoteserver

**Comment by Hi-Fi** [comment]
@lasselindqvist Sorry, have missed this PR completely somehow. If you're interested, you can also get rights to this repo to maintain the library.

Related to PR there's conflict now, that prevents merging.

**Comment by lasselindqvist** [comment]
> @lasselindqvist Sorry, have missed this PR completely somehow. If you're interested, you can also get rights to this repo to maintain the library.
> 
> Related to PR there's conflict now, that prevents merging.

Maybe https://github.com/robotframework/jrobotremoteserver/commit/cb0de38db898c98b6c2c6ea08c1764f96c7b3064 already included these fixes, just without the tests.

**Comment by Leemur89** [comment]
hello, are there any update on this MR? I am facing the same issue and it is blocking me too
thanks :)

**Comment by Leemur89** [comment]
> > @lasselindqvist Sorry, have missed this PR completely somehow. If you're interested, you can also get rights to this repo to maintain the library.
> > Related to PR there's conflict now, that prevents merging.
> 
> Maybe [cb0de38](https://github.com/robotframework/jrobotremoteserver/commit/cb0de38db898c98b6c2c6ea08c1764f96c7b3064) already included these fixes, just without the tests.

Maybe, but the commit you mentioned was not released (commit on DEC2022 but latest release is from MAR2022)...
Do you know if people are still maintaining this repo?

**Comment by lasselindqvist** [comment]
> > > @lasselindqvist Sorry, have missed this PR completely somehow. If you're interested, you can also get rights to this repo to maintain the library.
> > > Related to PR there's conflict now, that prevents merging.
> > 
> > 
> > Maybe [cb0de38](https://github.com/robotframework/jrobotremoteserver/commit/cb0de38db898c98b6c2c6ea08c1764f96c7b3064) already included these fixes, just without the tests.
> 
> Maybe, but the commit you mentioned was not released (commit on DEC2022 but latest release is from MAR2022)... Do you know if people are still maintaining this repo?

I did release this fix to Maven Central if someone needs it https://mvnrepository.com/artifact/io.github.lasselindqvist/jrobotremoteserver
Of course it would be nicer if this was maintained still.

**Comment by Hi-Fi** [comment]
@lasselindqvist @Leemur89 As mentioned in the comments, this can't be merged without conflict being fixed.

**Comment by lasselindqvist** [comment]
> @lasselindqvist @Leemur89 As mentioned in the comments, this can't be merged without conflict being fixed.

Yes. Like said, this has been included in the code base already without the tests, so I will close now. Those who want a maintained released version from Maven Central can use the fork if they wish.

**Comment by Hi-Fi** [comment]
@lasselindqvist I also suggested that you can be maintainer in this repo that's kind of easier to find, but with open source world forks can be done also.

**Pull request closed without merging**
